# This is the config file of parallel kMC program.
# file format: yaml, see https://yaml.org for mor e details.
# config template file writen by <a href='mailto:genshenchu@gmail.com'>genshen</a>"

title: "parallel kMC configure file"
version: "0.1.0"

box:
  size: [40, 40, 40]
  lattice_const: 2.85532   # lattice constance
  cutoff_radius: 5.6

create: # how the simulation box is created.
  random:
    enable: true
    va_count: 1   # vacancy number, not percent.
    alloy:
      Fe: 985
      Cu: 15
      Mn: 0
      Ni: 0
      FeFe: 0 # pair number of [110] dumbbell.
      FeCu: 0
      FeMn: 0
      FeNi: 0
      CuCu: 0
      CuNi: 0
      CuMn: 0
      NiNi: 0
      NiMn: 0
      MnMn: 0
  pipe: # if create_box is set to false or not set, then pipe will be used.
    enable: false
    input_box: last_frame.xyz # pipe from MD.
  restart:
    enable: false
    file_path: 1072.xyz

seeds:
  seeds_file: "" # used for setting different seed for each MPI rank (todo)
  create_types: 100565 # if 0 is set, random device will be used.
  create_vacancy: 16650
  event_selection: 563264
  time_inc: 594689

simulation:
  temperature: 573.15  # unit: K
  physics_time: 8e4  # physics time limit.
  steps_limit: 1000 # limit of kMC steps.
  attempt_freq: 6e12 #  unit:  1/s
  isgenr: false
  dpasm1: 3e-9 # dpa per second, unit: dpa/s

output:
  dump:
    interval: 1000 # dump system lattice information.
    file_path: "kmc.{}.xyz"
  logs:
    interval: 10 # if zero is set, it means no log.
    logs_file: "" # if it is empty, log to /dev/console
